// SFX resource specs

const ResSFX = {
// list of Audio-s used in the application
// sounds: soundId -> { src: src }
sounds: {
	"bloop": { src: "res/bloop.mp3" },
	"telept": { src: "res/telept.mp3" },
	"construct": { src: "res/construct.ogg", gain: 4.0, loop: true },
	"placement": { src: "res/placement.mp3", gain: 4.0 },
	"change_screen": { src: "res/change_screen.mp3", gain: 4.0 },
	"chimes": { src: "res/chimes.mp3" },
	"beep-beep-1": { src: "res/beep-beep-1.mp3" },
	"beep-beep-2": { src: "res/beep-beep-2.mp3" },
	"music_gameover": { src: "res/music_gameover.mp3", loop: false, gain: 2.0 },
	"music_abort": { src: "res/music_abort.mp3", loop: false, gain: 2.0 },
	"music_1": { src: "res/music_1.mp3", loop: true },
	"music_2": { src: "res/music_2.mp3", loop: true, gain: 2.0 },
	"music_3": { src: "res/music_3.mp3", loop: true, gain: 2.0 },
	"music_zona": { src: "res/music_zona.ogg", loop: true, gain: 2.0 },
	"music_chad_kutezh": { src: "res/music_chad_kutezh.mp3", loop: true, gain: 2.0 },
	"music_gameover": { src: "res/music_gameover.mp3", loop: false, gain: 4.0 },
	"hero_step_1": { src: "res/hero_step_1.mp3" },
	"hero_step_2": { src: "res/hero_step_2.mp3" },
	"hero_step_3": { src: "res/hero_step_3.mp3" },
	"hero_step_4": { src: "res/hero_step_4.mp3" },
	"explosion": { src: "res/explosion.mp3", gain: 2.0 }, // far
	"explosion2": { src: "res/explosion2.mp3", gain: 3.0 }, // close
	"pistol": { src: "res/pistol.mp3" },
	"kick": { src: "res/kick.mp3" },
	"facedrop": { src: "res/facedrop.mp3" },
	"train": { src: "res/train.mp3", gain: 6.0, loop: true },
	"train_beep": { src: "res/train_beep.mp3" },
	"train_brake": { src: "res/train_brake.mp3", gain: 6.0 },
	"tractor": { src: "res/tractor.mp3", gain: 3.0 },
	"tractor_honk": { src: "res/tractor_honk.mp3", gain: 3.0 },
	"tractor_bump": { src: "res/tractor_bump.mp3", gain: 3.0 },
	"pig": { src: "res/pig.mp3", gain: 2.0 },
	"squish": { src: "res/squish.mp3", gain: 3.0 },
	"khe1": { src: "res/khe1.mp3", gain: 3.0 },
	"khe2": { src: "res/khe2.mp3", gain: 3.0 },
	"item_fall": { src: "res/item_fall.mp3" },
	"bubbling": { src: "res/bubbling.ogg", gain: 4.0 },
	"lazer": { src: "res/lazer.mp3", gain: 4.0 },
	"nuke": { src: "res/nuke.mp3", gain: 4.0 },
	"chpok": { src: "res/chpok.mp3", gain: 3.0 },
	"ouch": { src: "res/ouch.mp3", gain: 2.0 },
	"buildup": { src: "res/buildup.mp3", gain: 6.0 },
	"detector": { src: "res/detector.mp3", gain: 4.0 },
	"sapog": { src: "res/sapog.ogg", gain: 3.0 },
	"gcock": { src: "res/gcock.mp3", gain: 6.0 },
	"boot": { src: "res/boot.ogg", gain: 2.0 },
	"boo": { src: "res/boo.mp3", gain: 3.0 },
	"bzzz": { src: "res/bzzz.ogg", gain: 5.0 },
	"mk152_hack": { src: "res/mk152_hack.mp3", gain: 3.0 },
},

// list of SFX groups used in the application: groupID -> [sfx spec]
// sfx-spec:
// sfx_id -> [ soundId ]
// note sfx-ids are assumed global, so no 2 groups must contain same sfx-id
sfxGroups: {
	"sfxGrpGame": {
		"bloop": ["bloop"],
		"telept": ["telept"],
		"construct": ["construct"],
		"placement": ["placement"],
		"change_screen": ["change_screen"],
		"chimes": ["chimes"],
		"beep-beep-1": ["beep-beep-1"],
		"beep-beep-2": ["beep-beep-2"],
		"music_gameover": ["music_gameover"],
		"music_abort": ["music_abort"],
		"music_1": ["music_1"],
		"music_2": ["music_2"],
		"music_3": ["music_3"],
		"music_zona": ["music_zona"],
		"music_chad_kutezh": ["music_chad_kutezh"],
		"music_gameover": ["music_gameover"],
		"hero_step_1": ["hero_step_1"],
		"hero_step_2": ["hero_step_2"],
		"hero_step_3": ["hero_step_3"],
		"hero_step_4": ["hero_step_4"],
		"explosion": ["explosion"],
		"explosion2": ["explosion2"],
		"pistol": ["pistol"],
		"kick": ["kick"],
		"facedrop": ["facedrop"],
		"tractor": ["tractor"],
		"train": ["train"],
		"train_beep": ["train_beep"],
		"train_brake": ["train_brake"],
		"tractor_honk": ["tractor_honk"],
		"tractor_bump": ["tractor_bump"],
		"pig": ["pig"],
		"squish": ["squish"],
		"khe1": ["khe1"],
		"khe2": ["khe2"],
		"item_fall": ["item_fall"],
		"bubbling": ["bubbling"],
		"lazer": ["lazer"],
		"nuke": ["nuke"],
		"chpok": ["chpok"],
		"ouch": ["ouch"],
		"buildup": ["buildup"],
		"detector": ["detector"],
		"sapog": ["sapog"],
		"gcock": ["gcock"],
		"boot": ["boot"],
		"boo": ["boo"],
		"bzzz": ["bzzz"],
		"mk152_hack": ["mk152_hack"],
	}
}

};

exports.ResSFX = ResSFX; // enable acquisition from node.js

