// Map tile resource specs
// Map tile name matches name of gfx in ResGFX.gfxGrpGame that originates
// from "maptile" sheet

const ResMapTiles = {
	"map_grass_0": { attr: ["pass"] },
	"map_grass_1": { attr: ["pass"] },
	"map_grass_2": { attr: ["pass"] },
	"map_dirt_0": { attr: ["pass"] },
	"map_dirt_1": { attr: ["pass"] },
	"map_dirt_2": { attr: ["pass"] },
	"map_dirt_3": { attr: ["pass"] },
	"map_water_0": { attr: ["nopass"] },
	"map_water_1": { attr: ["nopass"], tileAnimId: "MapWater" },
	"map_water_2": { attr: ["nopass"] },
	"map_water_3": { attr: ["nopass"] },
	"map_badwater_0": { attr: ["nopass"] },
	"map_badwater_1": { attr: ["nopass"], tileAnimId: "MapBadWater" },
	"map_badwater_2": { attr: ["nopass"] },
	"map_badwater_3": { attr: ["nopass"] },
	"map_rails_hz": { attr: ["pass"] },
	"map_rails_vt": { attr: ["pass"] },
	"map_rails_turn": { attr: ["pass"] },
	"map_forest_0": { attr: ["nopass"] },
	"map_forest_1": { attr: ["nopass"] },
	"map_forest_2": { attr: ["nopass"] },
	"map_forest_3": { attr: ["nopass"] },
	"map_tractr_hz": { attr: ["pass"] },
	"map_tractr_vt": { attr: ["pass"] },
	"map_tractr_hzvt": { attr: ["pass"] },
	"map_badforest_0": { attr: ["nopass"] },
	"map_badforest_1": { attr: ["nopass"] },
	"map_badforest_2": { attr: ["nopass"] },
	"map_badforest_3": { attr: ["nopass"] },
	"map_zone_0": { attr: ["pass"] },
	"map_woodfence_0": { attr: ["nopass"] },
	"map_woodfence_1": { attr: ["nopass"] },
	"map_woodfence_2": { attr: ["nopass"] },
	"map_woodfence_3": { attr: ["nopass"] },
	"map_stonefence_0": { attr: ["nopass"] },
	"map_barbedfence_0": { attr: ["nopass"] },
	"map_barbedfence_1": { attr: ["nopass"] },
	"map_woodfloor_0": { attr: ["pass"] },
	"map_woodfloor_1": { attr: ["pass"] },
	"map_woodfloor_2": { attr: ["pass"] },
	"map_woodwall_0": { attr: ["nopass"] },
	"map_woodwall_1": { attr: ["nopass"] },
	"map_woodwall_2": { attr: ["nopass"] },
	"map_woodwall_3": { attr: ["nopass"] },
	"map_woodwall_4": { attr: ["nopass"] },
	"map_woodwall_5": { attr: ["nopass"] },
	"map_luxfloor_0": { attr: ["pass"] },
	"map_luxwall_0": { attr: ["nopass"] },
	"map_bunkfloor_0": { attr: ["pass"] },
	"map_bunkfloor_1": { attr: ["pass"] },
	"map_bunkfloor_2": { attr: ["pass"] },
	"map_bunkwall_0": { attr: ["nopass"] },
	"map_bunkwall_1": { attr: ["nopass"] },
	"map_bunkwall_2": { attr: ["nopass"] },
	"map_bunkwall_3": { attr: ["nopass"] },
	"map_nopass": { attr: ["+nopass"] },
	"map_pass": { attr: ["-nopass"] },
	"map_empty": { attr: ["nopass"] },
};

exports.ResMapTiles = ResMapTiles; // enable acquisition from node.js
