// node compile_res_gfx.js
var ResGFX = require(__dirname + '/../res_gfx.js').ResGFX;

const fs = require('fs');
const extensionRegexp = /\.([^.]+)$/;
const dataTypes = {
	"png": "image/png"
};

for (var sheetId in ResGFX.sheets) {
	var sheet = ResGFX.sheets[sheetId];
	var dataType = dataTypes[extensionRegexp.exec(sheet.src)[1]]
		|| "";

	let buff = fs.readFileSync(__dirname + '/../' + sheet.src);
	var encoded = buff.toString('base64');
	sheet.src = "data:" + dataType + ";base64," + encoded;
}

fs.writeFileSync(__dirname + "/../res_gfx.gen.js",
"// this file is generated by compile_res_gfx.js, do not edit!\n"
+ "const ResGFX = \n"
+ JSON.stringify(ResGFX, null, '\t') + "\n"
+ ";"
);